commands:
  gdc-extract:
    image_name: biostream/gdc-extract
    cmd: ["/opt/gdc-scan.py", "cases", "list"]

variables:
  gdc-cases.json:
    type: multiline-json
    tags: ["gdc-cases"]

processes:
  - key: gdc-extract
    command: gdc-extract
    inputs: []
    outputs:
      /tmp/out: gdc-cases.json

agents:
  trigger: ["gdc-cases"]
  action: split-cases
